on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on pushs
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.sl1967.web.hostpoint.ch
        username: ${{ secrets.FTP_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /livuss.ch/